# Generated by Django 3.2.5 on 2021-07-25 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210722_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_bid',
            name='listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.auction_listing'),
        ),
        migrations.AlterField(
            model_name='auction_bid',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
