# Generated by Django 3.2.5 on 2021-07-26 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_listing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listings', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.auction_listing')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='watchlistuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
